// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoqsavtnkyamfclotqde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvcXNhdnRua3lhbWZjbG90cWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTY4NTMsImV4cCI6MjA2MDY3Mjg1M30.oNZOcIui8z9b_3t08cgWQa3FmCbOvvSHa949qr8liFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);